# Generated by Django 2.2.10 on 2021-05-29 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToppingCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.CharField(max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('inventory', models.ManyToManyField(blank=True, related_name='toppingcount', to='orders.ItemCost')),
            ],
        ),
    ]
