# Generated by Django 2.2.10 on 2021-05-29 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210528_2329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemcost',
            old_name='size',
            new_name='name',
        ),
    ]
