# Generated by Django 2.2.10 on 2021-05-30 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20210528_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='image',
            field=models.ImageField(blank=True, upload_to='image_inventory'),
        ),
    ]
