# Generated by Django 2.2.10 on 2021-05-30 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_inventory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='image',
            field=models.ImageField(blank=True, default='/image_inventory/pizza.jpg', upload_to='image_inventory'),
        ),
    ]
