# Generated by Django 2.2.10 on 2021-05-31 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20210531_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('item', models.ManyToManyField(blank=True, related_name='item', to='orders.ItemCost')),
            ],
        ),
    ]
