# Generated by Django 2.2.10 on 2021-05-31 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20210530_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='image',
            field=models.ImageField(blank=True, upload_to='image_inventory'),
        ),
    ]
