# Generated by Django 2.2.10 on 2021-05-31 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20210531_1446'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orden',
        ),
    ]
