# Generated by Django 2.2.10 on 2021-05-31 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20210531_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderr',
            name='status',
            field=models.CharField(choices=[('Initiated', 'Initiated'), ('Completed', 'Completed'), ('Refunded', 'Refunded')], default='Initiated', max_length=64),
        ),
    ]
