# Generated by Django 2.2.10 on 2021-05-31 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0015_auto_20210531_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderr',
            name='user_id',
        ),
        migrations.AddField(
            model_name='orderr',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
