# Generated by Django 2.2.10 on 2021-06-04 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0016_auto_20210531_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderr',
            name='status',
        ),
        migrations.RemoveField(
            model_name='orderr',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='completed_order_ids',
            name='status',
            field=models.CharField(choices=[('Initiated', 'Initiated'), ('Completed', 'Completed'), ('Refunded', 'Refunded')], default='Initiated', max_length=64),
        ),
        migrations.AddField(
            model_name='completed_order_ids',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='completed_order_ids',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
