# Generated by Django 2.2.10 on 2021-06-04 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_auto_20210603_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderr',
            name='order_id',
        ),
        migrations.AlterField(
            model_name='completed_order_ids',
            name='order_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.Orderr'),
        ),
    ]
