# Generated by Django 2.2.10 on 2021-06-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_auto_20210603_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completed_order_ids',
            name='order_id',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
