# Generated by Django 2.2.10 on 2021-07-06 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_remove_completed_order_ids_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='completed_order_ids',
            name='order_id',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
