# Generated by Django 2.2.10 on 2021-07-06 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_completed_order_ids_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completed_order_ids',
            name='order_id',
        ),
    ]
