# Generated by Django 2.2.10 on 2021-07-06 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_remove_completed_order_ids_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderr',
            name='order_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.Completed_Order_Ids'),
        ),
    ]
