# Generated by Django 2.2.10 on 2021-07-06 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_auto_20210706_0019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completed_order_ids',
            name='order_detail',
        ),
        migrations.RemoveField(
            model_name='completed_order_ids',
            name='user',
        ),
        migrations.AddField(
            model_name='completed_order_ids',
            name='order_id',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderr',
            name='order_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.Completed_Order_Ids'),
        ),
    ]
