# Generated by Django 2.2.10 on 2021-07-06 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_auto_20210706_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completed_order_ids',
            name='order_id',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
