# Generated by Django 2.2.10 on 2021-07-06 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_auto_20210706_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completed_order_ids',
            name='order_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.Orderr'),
        ),
    ]
