# Generated by Django 2.2.10 on 2021-07-06 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0028_auto_20210706_0111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completed_order_ids',
            name='order_id',
        ),
        migrations.AddField(
            model_name='completed_order_ids',
            name='item',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='completed_order_ids',
            name='toppings',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='completed_order_ids',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
