# Generated by Django 2.2.10 on 2021-07-09 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_auto_20210706_0115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completed_order_ids',
            name='item',
        ),
        migrations.RemoveField(
            model_name='completed_order_ids',
            name='toppings',
        ),
        migrations.AddField(
            model_name='completed_order_ids',
            name='order_detail',
            field=models.CharField(blank=True, max_length=800),
        ),
    ]
