# Generated by Django 2.2.10 on 2021-07-09 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_auto_20210709_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completed_order_ids',
            name='order_detail',
        ),
    ]
