# Generated by Django 2.2.10 on 2021-07-09 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0032_auto_20210709_1748'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Completed_Order_Ids',
        ),
    ]
