# Generated by Django 2.2.10 on 2021-07-10 00:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0034_completed_order_ids'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Completed_Order_Ids',
            new_name='Completed_Orders',
        ),
    ]
