# Generated by Django 2.2.10 on 2021-07-10 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0035_auto_20210709_1808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='completed_orders',
            old_name='user_id',
            new_name='user',
        ),
    ]
